import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../public/logo.png";
import skodaLogo from "../public/skoda.png";

const inter = Inter({ subsets: ["latin"] });

const getResponse = async () => {
     let response = await fetch(
          `${process.env.strapiAdress}/api/tests/${process.env.testId}?populate=*`,
          {
               headers: {
                    Authorization: `bearer ${process.env.bearerToken}`,
               },
          }
     );
     if (!response.ok) {
          throw new Error("Nie udało się pobrać danych");
     }
     response = await response.json();

     return response.data.attributes;
};

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default async function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     const data = await getResponse();
     console.log(data);
     return (
          <html lang="en">
               <body className="flex flex-col items-center justify-center py-8 px-24 mx-auto">
                    <div className="w-[1200px]">
                         <div className="flex items-center justify-between p-2 w-1200px">
                              <div>
                                   <Image
                                        width={307}
                                        height={74}
                                        src={logo}
                                        alt="logo"
                                   />
                              </div>

                              <div className="border-solid border-2 border-green-300 w-9/12 mx-4 my-8" />

                              <div>
                                   <Image
                                        width={160}
                                        height={64}
                                        // src={skodaLogo}
                                        src={`${process.env.strapiAdress}${data.partner_logo.data.attributes.url}`}
                                        alt="logo"
                                   />
                              </div>
                         </div>
                         {children}
                    </div>
               </body>
          </html>
     );
}
